[package]
name = "advent_of_code_25"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.53", features = ["derive"] }
tracing = "0.1.43"
tracing-subscriber = { version = "0.3.22", features = ["fmt"] }
anyhow = "1.0.100"
thiserror = "2.0.17"
